fix editor z-index position
beancount/fava pull request #1218
Opened 2021-01-14 23:31 UTC by ksesong

The editor is positioned on top of floating components, which is especially visible on help pages, and on the query or editor page when the header overlays (file selector, filters...) are active. This style sets the editor `z-index` to `0`.

![image](https://user-images.githubusercontent.com/940567/104660495-f5115800-56c6-11eb-89ab-897571e7163f.png)

2021-01-15 16:47 UTC, yagebu requested changes
Thanks for this fix!

CSS variables are used in all the other places where we set a `z-index`, which makes it easier to ensure they're correctly ranked. Could you also set and use a CSS variable for this value?

2021-01-15 23:32 UTC, ksesong commented
I named it as `--z-index-editor` if we want to stay specific to the editor.

2021-01-16 08:51 UTC, yagebu approved these changes

2021-01-16 08:52 UTC, yagebu commented
Thanks again :)

2021-01-16 08:52 UTC, merged