Support rendering qfx documents in editor
beancount/fava pull request #1274
Opened 2021-05-16 02:21 UTC by jeffwheeler

`.qfx` files are plain-text, and therefore can be viewed in the document editor just like `.csv` and `.txt`.

2021-05-16 07:48 UTC, yagebu requested changes
Thanks for the PR, just left a minor comment.

2021-05-16 07:48 UTC, yagebu commented on frontend/src/documents/DocumentPreview.svelte
> +{:else if ["csv", "txt", "qfx"].includes(extension)}
Now that this list gets longer, I think I would prefer to move it to the top as a `plainTextExtensions` next to `imageExtensions`

2021-05-18 01:52 UTC, jeffwheeler commented on frontend/src/documents/DocumentPreview.svelte
> +  const plainTextExtensions = ["csv", "txt", "qfx"];
Note that `prettier` prefers this all on one line, instead of broken into multiple lines like `imageExtensions`.

2021-05-30 08:17 UTC, yagebu approved these changes
Thanks :)

2021-05-30 08:18 UTC, merged